---
name: 'Build container'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Get image release
        id: release
        run: |
          # gets the list of all date-shaped tags for the image, finds the most recent one
          tag="$(skopeo list-tags "docker://ghcr.io/${{ github.repository }}" | \
            jq -r '.Tags | sort | reverse | map(select(test("^[0-9]{8}(R[0-9]+)?$")))[0]')"
          # tags from a different day or pre-YYYYMMDDRN
          if [ "${tag%R*}" != "$(date -u +%Y%m%d)" ] || [ "${tag%R*}" = "${tag}" ]; then
            rel=1
          else
            rel=$(( ${tag##*R} + 1 ))
          fi
          echo "rel=${rel}" >> "${GITHUB_OUTPUT}"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD'}}R${{ steps.release.outputs.rel }},enable={{is_default_branch}},priority=1000
          flavor: latest=false
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCHR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        id: build_and_push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
